app:
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen: ':7007'

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  providers:
    gcp-iap:
      audience: '/projects/${PROJECT_NUMBER}/global/backendServices/${BACKEND_ID}'
      signIn:
        resolvers:
          - resolver: emailMatchingUserEntityProfileEmail
          - resolver: emailLocalPartMatchingUserEntityName
          - resolver: emailMatchingUserEntityAnnotation

catalog:
  processingInterval: { minutes: 5 }
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules: 
    - allow: [Component, Group, User, Resource, Location, Template, System]
  locations:
    - type: url
      target: https://github.com/RyuSA/seagull-backstage/blob/main/catalogs/lookup.yaml

techdocs:
  builder: 'external'
  publisher:
    type: 'googleGcs'
    googleGcs:
      bucketName: ${BUTCKET_NAME}
      projectId: ${PROJECT_ID}

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'gke'
      projectId: ${PROJECT_ID}
      region: ${REGION}
      skipTLSVerify: true
      authProvider: 'googleServiceAccount'