
steps:
  - name: node:20
    entrypoint: yarn
    args: ["install", "--frozen-lockfile"]
  - name: node:20
    entrypoint: yarn
    args: ["tsc"]
  - name: node:20
    entrypoint: yarn
    args: ["build:backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", ".", "-f", "packages/backend/Dockerfile" , "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/backstage/backstage:latest"]
    env:
    - "DOCKER_BUILDKIT=1"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/backstage/backstage:latest"

substitutions:
  _REGION: asia-northeast1
