apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: seagull-family
  description: A collection of all entities
spec:
  type: url
  targets:
    - https://github.com/RyuSA/seagull-backstage/blob/main/catalog-info.yaml
    - https://github.com/RyuSA/x-ctf/blob/main/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: RyuSA
spec:
  profile:
    displayName: RyuSA
    email: ryusa@example.com
    picture: https://avatars.githubusercontent.com/u/12961775
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  profile:
    displayName: Guests
  children: []
