apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backstage
    backstage.io/kubernetes-id: backstage
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
        backstage.io/kubernetes-id: backstage
    spec:
      serviceAccountName: backstage
      containers:
      - image: ryusa/backstage:latest
        args: ["--config", "/config/app-config.production.yaml"]
        name: backstage
        resources: 
          requests:
            cpu: "600m"
            memory: "500Mi"
          limits:
            cpu: "600m"
            memory: "500Mi"
        ports:
          - name: http
            containerPort: 7007
        env:
          - name: POSTGRES_HOST
            value: 127.0.0.1
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: backstage-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: backstage-secret
          - name: BUTCKET_NAME
            valueFrom:
              secretKeyRef:
                key: BUTCKET_NAME
                name: backstage-secret
          - name: PROJECT_ID
            valueFrom:
              secretKeyRef:
                key: PROJECT_ID
                name: backstage-secret
          - name: REGION
            valueFrom:
              secretKeyRef:
                key: REGION
                name: backstage-secret
          - name: PROJECT_NUMBER
            valueFrom:
              secretKeyRef:
                key: PROJECT_NUMBER
                name: backstage-secret
          - name: BACKEND_ID
            valueFrom:
              secretKeyRef:
                key: BACKEND_ID
                name: backstage-secret
        volumeMounts:
          - mountPath: /config
            name: config
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          - "--private-ip"
          - "--structured-logs"
          - "--auto-iam-authn"
          - $(CLOUD_SQL)
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            memory: "128Mi"
            cpu:    "250m"
          requests:
            memory: "128Mi"
            cpu:    "250m"
        env:
          - name: CLOUD_SQL
            valueFrom: # my-project:region:instance-name
              secretKeyRef:
                key: CLOUD_SQL
                name: backstage-secret
      volumes:
        - name: config
          configMap:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backstage
    backstage.io/kubernetes-id: backstage
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "iap-backendconfig"}'
  name: backstage
spec:
  ports:
  - port: 7007
    protocol: TCP
    targetPort: 7007
  selector:
    app: backstage
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: backstage-cert
spec:
  domains:
    - backstage.g.ryusa.app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: backstage
    networking.gke.io/managed-certificates: backstage-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: backstage
      port:
        number: 7007
