apiVersion: v1
data:
kind: Secret
metadata:
  name: iap-secret
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: iap-backendconfig
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-secret
